vich_uploader:
    db_driver: orm

    mappings:
        project_files:
            uri_prefix: /uploads/files
            upload_destination: '%kernel.project_dir%/var/uploads/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        project_images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/var/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
